### PR TITLE
Added Data science books and links for that books , and also added diff…

### PR DESCRIPTION
**Pull request by SadafKausar2025**
…erent imaged to look  gook

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
please assign this issue to me I have done a lot good looks in this website and also added good resources for data science students.

**Comment by aniketsinha2002** [comment]
@SadafKausar2025 Share a video of the working website after your changes!

**Comment by SadafKausar2025** [comment]
Screenshot (1676)
Screenshot (1677)

**Comment by SadafKausar2025** [comment]
hi @aniketsinha2002 
can you please add gssoc label in this PR

**Comment by SadafKausar2025** [comment]
hello @aniketsinha2002 
I have done a lot in this PR. but this is not counted in my gssoc point list
can you please assign me and give good level to it , so that it will be counted in my contribution.

**Comment by aniketsinha2002** [comment]
@SadafKausar2025 Let me know what label would be fine I'll add that.

**Comment by SadafKausar2025** [comment]
level3 or level2 , as per your wish

**Comment by aniketsinha2002** [comment]
Added!

**Comment by SadafKausar2025** [comment]
Hello @aniketsinha2002
Please also assign it otherwise it will not be counted

**Pull request merged**
